logging:
  level:
    org:
      springframework:
        security: info


spring:
  mvc:
    format:
      date-time: dd-MM-yyyy'T'HH:mm

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: calendar
    password: calendar
  h2:
    console:
      enabled: true
      path: /h2-console